DEMOAPP/Controllers/SubjectController.cs
using DEMOAPP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DEMOAPP.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ILogger<SubjectController> _logger;
        private DemoContext _context;

        public SubjectController(ILogger<SubjectController> logger, DemoContext _context)
        {
            _logger = logger;
            this._context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult SaveSubject(SubjectModel model)
        {
            try
            {
                using (DemoContext dbcontext = new DemoContext())
                {
                    var e = new Subject
                    {
                        SubId = model.Id,
                        SubName = model.Sub_Name,
                        Remark = model.Remark
                    };
                    dbcontext.Add(e);
                    dbcontext.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("Index");
        }
    }
}

DEMOAPP/Views/Subject/Create.cshtml
@model DEMOAPP.Models.SubjectModel
@using DEMOAPP.Models
@{
    ViewData["Title"] = "Create";
}
<div class="right-panel" style="padding-top:0;">
    <h1>Create sub</h1>
    <div class="clearfix">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div style="margin-top:10px;">
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    }
                </div>
                <div class="row">
                    <div class="col-sm-9">
                        <h4 class="no-margin" />
                    </div>
                    <div class="col-sm-3">
                        <div class="text-right">
                            <a asp-action="Index" class="btn btn-primary"><i class="fa fa-reply" aria-hidden="true"></i> Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <form method="post" asp-controller="Subject" asp-action="SaveSubject" id="" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label asp-for="Sub_Name"></label><span class="text-danger">*</span>
                        </div>
                        <div class="col-md-4">
                            <input asp-for="Sub_Name" class="form-control" name="Sub_Name" />
                            <span asp-validation-for="Sub_Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label asp-for="Remark"></label><span class="text-danger">*</span>
                        </div>
                        <div class="col-md-4">
                            <input asp-for="Remark" class="form-control" name="Remark" />
                            <span asp-validation-for="Remark" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <input type="submit" value="SaveSubject" class="btn btn-primary" id="Add" />
                            <a asp-controller="Subject" asp-action="Index" type="button" class="btn  btn-danger">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

DEMOAPP/Views/Subject/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>