DEMOAPP/Controllers/UseProcedureController.cs
using DEMOAPP.Helper;
using DEMOAPP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;

namespace DEMOAPP.Controllers
{
    public class UseProcedureController : Controller
    {
        public IActionResult Index()
        {
            var ds = new DataSet();
            StudentInfo model = new StudentInfo();
            using (DemoContext dbcontext = new DemoContext())
            {
                dbcontext.Database.OpenConnection();
                DbCommand cmd = dbcontext.Database.GetDbConnection().CreateCommand();
                cmd.CommandText = "USP_STUDENT";
                cmd.CommandType = CommandType.StoredProcedure;
                DbParameter[] parametes = new DbParameter[] { };
                var parameters = new[]{
                    new SqlParameter(){ ParameterName="@FLAG", Value="S" }
                };
                cmd.Parameters.AddRange(parameters);
                using (DbDataAdapter da = new SqlDataAdapter())
                {
                    da.SelectCommand = cmd;
                    da.Fill(ds);
                    model.StundetList = CommonMethod.ConvertToList<StudentModel>(ds.Tables[0]);
                    model.ddlStundet= CommonMethod.ConvertToList<ddlStudentModel>(ds.Tables[1]);
                }
            }
            return View(model);
        }
        public IActionResult AddStudent()
        {
            return View();
        }
        public IActionResult Create(StudentModel model)
        {
            try
            {
                using (DemoContext dbcontext = new DemoContext())
                {
                    dbcontext.Database.OpenConnection();
                    DbCommand cmd = dbcontext.Database.GetDbConnection().CreateCommand();
                    cmd.CommandText = "USP_STUDENT";
                    cmd.CommandType = CommandType.StoredProcedure;
                    DbDataReader sqlReader;

                    DbParameter[] parametes = new DbParameter[] { };
                    var parameters = new[]{
                    new SqlParameter(){ ParameterName="@FLAG", Value="I" },
                    new SqlParameter(){ ParameterName="@ID", Value=model.SID },
                    new SqlParameter(){ ParameterName="@NAME", Value=model.NAME },
                    new SqlParameter(){ ParameterName="@EMAIL", Value=model.EMAIL},
                    new SqlParameter(){ ParameterName="@CONTACT", Value=model.CONTACT}
                    };
                    cmd.Parameters.AddRange(parameters);
                    sqlReader = cmd.ExecuteReader();
                    if (sqlReader != null)
                    {
                        string a = "Record Save";
                    }
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return RedirectToAction("Index");
        }
    }

}

DEMOAPP/Views/UseProcedure/AddStudent.cshtml
@model DEMOAPP.Models.StudentModel
@using DEMOAPP.Models
@{
    ViewData["Title"] = "AddStudent";
}
<div class="right-panel" style="padding-top:0;">
    <h1>AddStudent</h1>
    <div class="clearfix">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div style="margin-top:10px;">
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    }
                </div>
                <div class="row">
                    <div class="col-sm-9">
                        <h4 class="no-margin" />
                    </div>
                    <div class="col-sm-3">
                        <div class="text-right">
                            <a asp-action="Index" class="btn btn-primary"><i class="fa fa-reply" aria-hidden="true"></i> Back to Student List</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <form method="post" asp-controller="UseProcedure" asp-action="Create" id="" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @*@Html.HiddenFor(x => x.Id)*@
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label asp-for="NAME"></label><span class="text-danger">*</span>
                        </div>
                        <div class="col-md-4">
                            <input asp-for="NAME" class="form-control" name="NAME" />
                            <span asp-validation-for="NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label asp-for="EMAIL"></label><span class="text-danger">*</span>
                        </div>
                        <div class="col-md-4">
                            <input asp-for="EMAIL" class="form-control" name="EMAIL" />
                            <span asp-validation-for="EMAIL" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label asp-for="CONTACT"></label><span class="text-danger">*</span>
                        </div>
                        <div class="col-md-4">
                            <input asp-for="CONTACT" class="form-control" name="CONTACT" />
                            <span asp-validation-for="CONTACT" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <input type="submit" value="Create" class="btn btn-primary" id="AddNewEmployee" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="~/js/Custom/ProjectManager.js"></script>

DEMOAPP/Views/UseProcedure/Index.cshtml
@model DEMOAPP.Models.StudentInfo
@{
    ViewData["Title"] = "Index";
}

<h1>Student List</h1>

<table border="1">
    <thead>
        <tr>
            <th colspan="2">Name</th>
            <th colspan="2">Email</th>

        </tr>
    </thead>
    <tbody>
        @{

            foreach (var item in Model.StundetList)
            {
                <tr>
                    <td rowspan="2"> @item.NAME</td>
                </tr>
                <tr>
                    <td colspan="2"> @item.EMAIL</td>
                </tr>
            }
            <tr colspan="8">
                <th rowspan="2"> ID</th>
                <th rowspan="2"> NAME</th>
            </tr>
            foreach (var item in Model.ddlStundet)
            {
                <tr>
                    <td rowspan="2"> @item.ID</td>
                </tr>
                <tr>
                    <td colspan="2"> @item.NAME</td>
                </tr>
            }

        }

    </tbody>
</table>